"""empty message

Revision ID: 0a32d8ae782b
Revises: 
Create Date: 2021-12-05 15:38:11.267898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a32d8ae782b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('continent', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('father_name', sa.String(length=64), nullable=False),
    sa.Column('mother_name', sa.Integer(), nullable=False),
    sa.Column('father_height', sa.Integer(), nullable=False),
    sa.Column('mother_height', sa.Integer(), nullable=False),
    sa.Column('father_weight', sa.Integer(), nullable=False),
    sa.Column('mother_weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('father_height', sa.Integer(), nullable=False),
    sa.Column('mother_height', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('parent')
    op.drop_table('country')
    # ### end Alembic commands ###
